### ISSUE TITLE
[Insight] Class should be unique per PHP file - in slacker.php, line 0

### ISSUE THREAD

**Issue by Tjoosten** [TidalLabs/Slacker#14]
**[in slacker.php](https://github.com/TidalLabs/Slacker/blob/87e74a41ff8650f9ea56f9c8b1e6a3f6648df3ca/slacker.php#L0)**

> This file contains 6 classes. Keeping only one class per file is a standard in the PHP community, since it promotes interoperability and maintainability.
- AuthException (defined at **[line 141]()**)
- Slack (defined at **[line 150]()**)
- Pane (defined at **[line 587]()**)
- MenuPane (defined at **[line 762]()**)
- RoomPane (defined at **[line 909]()**)
- Slacker (defined at **[line 975]()**)

---

**Comment by thattomperson** [comment]
this has been resolved in #12
