### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by stephenway** [TidalLabs/Slacker#15]
I'm unable to get homebrew/dupes/ncurses to wire up with Slacker. Any tips on getting the proper dependencies installed on this platform?

**Comment by bkanber** [comment]
I've never tried it on OSX, only on Linux. That being said, I'm sure it's
possible to get it to work, it just might take a bit of an effort. I'll
look into it and let you know if I figure anything out!

On Wed, Sep 9, 2015 at 6:52 PM, Stephen Way notifications@github.com
wrote:

> I'm unable to get homebrew/dupes/ncurses to wire up with Slacker. Any tips
> on getting the proper dependencies installed on this platform?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TidalLabs/Slacker/issues/15.

## 

```
 Burak Kanber
 CTO, Tidal Labs
 tid.al
 burakkanber.com
```
