### ISSUE TITLE
Manage/document prerequisites

### ISSUE THREAD

**Issue by lukewelling** [TidalLabs/Slacker#6]
Installed reasonably smoothly for me, except not obvious that I needed the dev version of ncurses to make it work.

Documenting pecl install and php.ini change for ncurses is probably a good thing as they are not common.

**Comment by bkanber** [comment]
Added 
- `make ubuntu-dependencies` command
- documentation to `make help` about dependencies
- documentation to readme.me about dependencies
- friendly ncurses extension check in the app itself
